### ISSUE TITLE
Why not xstate

### ISSUE THREAD

**Issue by jeetiss** [eunjae-lee/tiny-fsm#6]
Why you chose writing new library, while `xstate` has that option?) I mean small finite machine `@xstate/fsm`. This library is supported by visualizer and integrated in xstate ecosystem. What you motivation for the new one?

**Comment by eunjae-lee** [comment]
Hey 👋 
I'm on an experiment :)
One thing I wanted to have with `@xstate/fsm` was parallel states.
For parallel states, I had to use the whole package, which was too big.

So this is heavily inspired by `xstate/fsm` but with parallel states.
But I'm not sure how serious I am about this yet.

And like you said, I don't have a visualizer here.

**Comment by jeetiss** [comment]
Thanks for answer
